with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "mocker"
outpkg: "mocker"

packages:
  SyncthingHook/domain:
    config:
      all: true
  SyncthingHook/exevent:
    config:
      all: false
      dir: "{{.InterfaceDir}}"
      outpkg: "{{.PackageName}}"
      inpackage: True
    interfaces:
      cmdExecutor: