log:
  stdout:
    enabled: true
    level: info
  file:
    enabled: false
    level: info
    dir: ./
    max-size: 10 # MB
    max-backups: 3

syncthing:
  url: http://localhost:8384
  apikey: ""

hooks:
  - event-type: "ex:LocalFolderContentChangeDetected"
    parameter:
      st-folder: "xxxxx-yyyyy"
      path: "/"
      tolerance: 0
    action:
      type: "exec"
      cmd: [ '/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel', '--sync' ]